// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICasino;

#nullable disable

namespace WebAPICasino.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220427182035_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPICasino.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebAPICasino.Entidades.Rifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero14")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero15")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero16")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero17")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero18")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero19")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero21")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero22")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero23")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero24")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero25")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero26")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero27")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero28")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero29")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero30")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero31")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero33")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero34")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero35")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero36")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero37")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero38")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero39")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero40")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero41")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero42")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero43")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero44")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero45")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero46")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero47")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero48")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero49")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero50")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero51")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero52")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero53")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero54")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rifas");
                });
#pragma warning restore 612, 618
        }
    }
}
